version: "3.12"

services:

  redis:
    container_name: redis
    image: redis:latest
    restart: on-failure
    expose:
      - "6379"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=DW
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123123
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=DW
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123123
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
    postgres_data: